#' GSEA plot that mimic the plot generated by broad institute's GSEA software
#' @param x An `gseaResult` object returned by clusterProfiler.
#' @param geneSetID gene set ID
#' @param subplots which subplots to be displayed
#' @param rel_heights relative heights of subplots
#' @param ES_geom geom for plotting running enrichment score, one of 'line' or
#' 'dot'.
#' @param add_bar A bool, whether add a gsea bar in the second plot.
#' @return A `patchwork` object.
#' @references 
#' <https://github.com/YuLab-SMU/enrichplot/blob/devel/R/gseaplot.R>
#' @export 
gggsea <- function(x, geneSetID = NULL, subplots = 1:3, rel_heights = c(1.8, .4, 0.8), ES_geom = "line", add_bar = TRUE, ...) {
    assert_s4_class(x, "gseaResult")
    assert_inclusive(subplots, 1:3, null_ok = TRUE)
    geneSetID <- geneSetID %||% 1:3
    ES_geom <- match.arg(ES_geom, c("line", "dot"))
    geneSetID <- intersect(seq_len(nrow(x@result)), geneSetID)
    if (length(geneSetID) == 1L) {
        gsdata <- enrichplot:::gsInfo(x, geneSetID)
    } else {
        gsdata <- do.call(
            rbind,
            lapply(geneSetID, enrichplot:::gsInfo, object = x)
        )
    }

    p <- ggplot2::ggplot(gsdata, ggplot2::aes(x = .data$x)) +
        ggplot2::scale_x_continuous(name = NULL, expand = c(0, 0)) +
        ggplot2::theme_classic(base_size = 11) +
        ggplot2::theme(
            panel.grid.major = ggplot2::element_line(colour = "grey92"),
            panel.grid.minor = ggplot2::element_line(colour = "grey92"),
            panel.grid.major.y = ggplot2::element_blank(),
            panel.grid.minor.y = ggplot2::element_blank()
        )


    if (ES_geom == "line") {
        es_layer <- ggplot2::geom_line(
            ggplot2::aes(y = .data$runningScore, color = .data$Description),
            linewidth = 1L
        )
    } else {
        es_layer <- ggplot2::geom_point(
            ggplot2::aes(y = .data$runningScore, color = .data$Description),
            linewidth = 1L,
            data = ~ subset(.x, position == 1L)
        )
    }
    p.res <- p + es_layer +
        ggplot2::ylab("Running Enrichment Score") +
        ggplot2::theme(
            axis.text.x = ggplot2::element_blank(),
            axis.ticks.x = ggplot2::element_blank(),
            axis.line.x = ggplot2::element_blank(),
            plot.margin = ggplot2::margin(
                t = .2, r = .2, b = 0, l = .2, unit = "cm"
            )
        )


    # P2 ----------------------------------------------------------------
    i <- 0L
    for (term in unique(gsdata$Description)) {
        idx <- which(gsdata$ymin != 0L & gsdata$Description == term)
        gsdata[idx, "ymin"] <- i
        gsdata[idx, "ymax"] <- i + 1L
        i <- i + 1L
    }

    p2 <- ggplot2::ggplot(gsdata, ggplot2::aes(x = .data$x)) +
        ggplot2::geom_linerange(
            ggplot2::aes(
                ymin = .data$ymin, ymax = .data$ymax,
                color = .data$Description
            )
        ) +
        ggplot2::scale_x_continuous(name = NULL, expand = c(0, 0)) +
        ggplot2::scale_y_continuous(name = NULL, expand = c(0, 0)) +
        ggplot2::theme_classic(base_size = 11) +
        ggplot2::theme(
            legend.position = "none",
            plot.margin = ggplot2::margin(t = -.1, b = 0, unit = "cm"),
            axis.ticks = ggplot2::element_blank(),
            axis.text = ggplot2::element_blank(),
            axis.line.x = ggplot2::element_blank()
        )

    if (length(geneSetID) == 1L && add_bar) {
        v <- seq(1L, sum(gsdata$position), length.out = 9L)
        inv <- findInterval(rev(cumsum(gsdata$position)), v)
        if (min(inv) == 0L) inv <- inv + 1L

        col <- c(
            rev(RColorBrewer::brewer.pal(5, "Blues")),
            RColorBrewer::brewer.pal(5, "Reds")
        )

        ymin <- min(p2$data$ymin)
        yy <- max(p2$data$ymax - p2$data$ymin) * .3
        xmin <- which(!duplicated(inv))
        xmax <- xmin + as.numeric(table(inv)[as.character(unique(inv))])
        d <- data.frame(
            ymin = ymin, ymax = yy,
            xmin = xmin,
            xmax = xmax,
            col = col[unique(inv)]
        )
        p2 <- p2 + ggplot2::geom_rect(
            ggplot2::aes(
                xmin = .data$xmin, xmax = .data$xmax,
                ymin = .data$ymin, ymax = .data$ymax,
                fill = .env$col
            ),
            data = d,
            alpha = .9,
            inherit.aes = FALSE
        )
    }

    # P3
    df2 <- p$data # data.frame(x = which(p$data$position == 1))
    df2$y <- p$data$geneList[df2$x]
    p.pos <- p + ggplot2::geom_segment(
        ggplot2::aes(x = .data$x, xend = .data$x, y = .data$y, yend = 0),
        color = "grey", data = df2
    )

    p.pos <- p.pos + ggplot2::ylab("Ranked Metric") +
        ggplot2::xlab("Rank in Ordered Dataset")

    # Others
    plotlist <- list(p.res, p2, p.pos)[subplots]
    n <- length(plotlist)
    plotlist[[n]] <- plotlist[[n]] +
        ggplot2::theme(
            axis.line.x = ggplot2::element_line(),
            axis.ticks.x = ggplot2::element_line(),
            axis.text.x = ggplot2::element_text()
        )
    if (n == 1L) {
        return(
            plotlist[[1L]] + ggplot2::theme(
                plot.margin = ggplot2::margin(
                    t = .2, r = .2, b = .2, l = .2, unit = "cm"
                )
            )
        )
    }
    if (length(rel_heights) > length(subplots)) {
        rel_heights <- rel_heights[subplots]
    }
    patchwork::wrap_plots(
        plotlist = plotlist, ncol = 1L,
        heights = rel_heights
    )
}
