# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rrho_hyper_overlap_cpp <- function(sample1, sample2, stepsize) {
    .Call(`_biomisc_rrho_hyper_overlap_cpp`, sample1, sample2, stepsize)
}

